// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using registration.Models;

namespace registration.Migrations
{
    [DbContext(typeof(CMSContext))]
    partial class CMSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("registration.Models.CustomerModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("city");

                    b.Property<string>("email");

                    b.Property<string>("name");

                    b.Property<string>("st_addr");

                    b.Property<string>("tel");

                    b.Property<string>("zip");

                    b.HasKey("id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("registration.Models.UserModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("city");

                    b.Property<string>("email");

                    b.Property<string>("fname");

                    b.Property<string>("lname");

                    b.Property<string>("password");

                    b.Property<string>("st_addr");

                    b.Property<string>("tel");

                    b.Property<string>("username");

                    b.Property<string>("zip");

                    b.HasKey("id");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
